# CLEANING THE HEADERS

ALTER TABLE maindata CHANGE %Airline ID AIRLINE_ID INT;
ALTER TABLE maindata CHANGE %Carrier Group ID Carrier_Group_ID INT;
ALTER TABLE maindata CHANGE %Unique Carrier Code Unique_Carrier_Code TEXT;
ALTER TABLE maindata CHANGE %Unique Carrier Entity Code Unique_Carrier_Entity_Code INT;
ALTER TABLE maindata CHANGE %Region Code Region_Code TEXT;
ALTER TABLE maindata CHANGE %Origin Airport ID Origin_Airport_ID INT;
ALTER TABLE maindata CHANGE %Origin Airport Sequence ID Origin_Airport_Sequence_ID INT;
ALTER TABLE maindata CHANGE %Origin Airport Market ID Origin_Airport_Market_ID INT;
ALTER TABLE maindata CHANGE %Origin World Area Code Origin_World_Area_Code INT;
ALTER TABLE maindata CHANGE %Destination Airport ID Destination_Airport_ID INT;
ALTER TABLE maindata CHANGE %Destination Airport Sequence ID Destination_Airport_Sequence_ID INT;
ALTER TABLE maindata CHANGE %Destination Airport Market ID Destination_Airport_Market_ID INT;
ALTER TABLE maindata CHANGE %Destination World Area Code Destination_World_Area_Code INT;
ALTER TABLE maindata CHANGE %Aircraft Group ID Aircraft_Group_ID INT;
ALTER TABLE maindata CHANGE %Aircraft Type ID Aircraft_Type_ID INT;
ALTER TABLE maindata CHANGE %Aircraft Configuration ID Aircraft_Configuration_ID INT;
ALTER TABLE maindata CHANGE %Distance Group ID Distance_Group_ID INT;
ALTER TABLE maindata CHANGE %Service Class ID Service_Class_ID TEXT;
ALTER TABLE maindata CHANGE %Datasource ID Datasource_ID TEXT;
ALTER TABLE maindata CHANGE # Departures Scheduled Departures_Scheduled INT;
ALTER TABLE maindata CHANGE # Departures Performed Departures_Performed INT;
ALTER TABLE maindata CHANGE # Payload Payload INT;
ALTER TABLE maindata CHANGE Distance Distance INT;
ALTER TABLE maindata CHANGE # Available Seats Available_Seats INT;
ALTER TABLE maindata CHANGE # Transported Passengers Transported_Passengers INT;
ALTER TABLE maindata CHANGE # Transported Freight Transported_Freight INT;
ALTER TABLE maindata CHANGE # Transported Mail Transported_Mail INT;
ALTER TABLE maindata CHANGE # Ramp-To-Ramp Time Ramp_To_Ramp_Time INT;
ALTER TABLE maindata CHANGE # Air Time Air_Time INT;
ALTER TABLE maindata CHANGE Unique Carrier Unique_Carrier TEXT;
ALTER TABLE maindata CHANGE Carrier Code Carrier_Code TEXT;
ALTER TABLE maindata CHANGE Carrier Name Carrier_Name TEXT;
ALTER TABLE maindata CHANGE Origin Airport Code Origin_Airport_Code TEXT;
ALTER TABLE maindata CHANGE Origin City Origin_City TEXT;
ALTER TABLE maindata CHANGE Origin State Code Origin_State_Code TEXT;
ALTER TABLE maindata CHANGE Origin State FIPS Origin_State_FIPS INT;
ALTER TABLE maindata CHANGE Origin State Origin_State TEXT;
ALTER TABLE maindata CHANGE Origin Country Code Origin_Country_Code TEXT;
ALTER TABLE maindata CHANGE Origin Country Origin_Country TEXT;
ALTER TABLE maindata CHANGE Destination Airport Code Destination_Airport_Code TEXT;
ALTER TABLE maindata CHANGE Destination City Destination_City TEXT;
ALTER TABLE maindata CHANGE Destination State Code Destination_State_Code TEXT;
ALTER TABLE maindata CHANGE Destination State FIPS Destination_State_FIPS INT;
ALTER TABLE maindata CHANGE Destination State Destination_State TEXT;
ALTER TABLE maindata CHANGE Destination Country Code Destination_Country_Code TEXT;
ALTER TABLE maindata CHANGE Destination Country Destination_Country TEXT;
ALTER TABLE maindata CHANGE Year Years INT;
ALTER TABLE maindata CHANGE Month (#) Months INT;
ALTER TABLE maindata CHANGE Day Days INT;
ALTER TABLE maindata CHANGE From - To Airport Code From_To_Airport_Code TEXT;
ALTER TABLE maindata CHANGE From - To Airport ID From_To_Airport_ID TEXT;
ALTER TABLE maindata CHANGE From - To City From_To_City TEXT;
ALTER TABLE maindata CHANGE From - To State Code From_To_State_Code TEXT;
ALTER TABLE maindata CHANGE From - To State From_To_State TEXT;
ALTER TABLE aircraft_groups CHANGE ï»¿%Aircraft Group ID Aircraft_Group_ID INT;
ALTER TABLE aircraft_groups CHANGE Aircraft Group Aircraft_Group TEXT;
ALTER TABLE aircraft_types CHANGE ï»¿%Aircraft Type ID Aircraft_Type_ID TEXT;
ALTER TABLE aircraft_types CHANGE Aircraft Type Aircraft_Type TEXT;
ALTER TABLE airlines CHANGE ï»¿%Airline ID Airline_ID INT;
ALTER TABLE airlines CHANGE Airline Airline TEXT;
ALTER TABLE carrier_groups CHANGE ï»¿%Carrier Group ID Carrier_Group_ID INT;
ALTER TABLE carrier_groups CHANGE Carrier Group Carrier_Group TEXT;
ALTER TABLE carrier_operating_region CHANGE ï»¿%Region Code Region_Code TEXT;
ALTER TABLE carrier_operating_region CHANGE Carrier Operating Region Carriers_Operating_Region TEXT;
ALTER TABLE destination_markets CHANGE %Destination Airport Market ID Destination_Airport_Market_ID INT;
ALTER TABLE destination_markets CHANGE Destination Market Destination_Market TEXT;
ALTER TABLE distance_groups CHANGE ï»¿%Distance Group ID Distance_Group_ID INT;
ALTER TABLE distance_groups CHANGE Distance Interval Distance_Interval TEXT;
ALTER TABLE flight_types CHANGE ï»¿%Datasource ID Datasource_ID TEXT;
ALTER TABLE flight_types CHANGE Flight Type Flight_Type TEXT;
ALTER TABLE origin_markets CHANGE %Origin Airport Market ID Origin_Airport_Market_ID INT;
ALTER TABLE origin_markets CHANGE Origin Market Origin_Market TEXT;
